import { SkillData, ProductId, ChainId, CoverTemplateId, TitleTemplateId, PageTemplateId, CopyFormatId, HotTitle } from '@/types/data';

const formulaRows: Array<[string, string, TitleTemplateId]> = [
  ['1', '为什么 [每个人都觉得很好的事] 其实对你有害？', 'not_a_but_b'],
  ['2', '为什么 [非传统操作] 是对 [目标] 有益的', 'not_a_but_b'],
  ['3', '为什么我不 [绝大多数人做的事]', 'dont_only'],
  ['4', '[行动] [行动] [行动] 的共同好处', 'checklist_ready'],
  ['5', '为什么 [话题] 会改变一切', 'not_a_but_b'],
  ['6', '犯了 [不同寻常的错]，我反而 [好结果]', 'not_a_but_b'],
  ['7', '[一群人] 不会告诉你的建议', 'not_a_but_b'],
  ['8', '[专家们] 不想让你知道的 [数字] 件事', 'checklist_ready'],
  ['9', '达到 [结果]，令人意想不到的秘密', 'not_a_but_b'],
  ['10', '[结果] 让你想不到的秘密', 'not_a_but_b'],
  ['11', '关于 [某件事]，[一群人] 太晚知道的 [数字] 个教训', 'mistake_warning'],
  ['12', '看完这个，你的 [想法] 会不再相同', 'not_a_but_b'],
  ['13', '[不想要的结果] 的最快方法', 'mistake_warning'],
  ['14', '[不想要的结果] 的最根本原因', 'mistake_warning'],
  ['15', '[数字] 件阻碍你达成 [结果] 的事', 'mistake_warning'],
  ['16', '[行为] 的后果', 'mistake_warning'],
  ['17', '警告！[数字] 件事正让你的 [努力] 白费', 'mistake_warning'],
  ['18', '[平台/领域] 上这 [数字] 件事千万别做', 'mistake_warning'],
  ['19', '[一群人] 常犯的 [数字] 个错误', 'mistake_warning'],
  ['20', '[数字] 个最危险的 [话题]', 'mistake_warning'],
  ['21', '给每个 [年龄层/身份] 人的终极 [建议]', 'checklist_ready'],
  ['22', '为 [某种特质的人] 量身定制的 [方案]', 'checklist_ready'],
  ['23', '给 [一群人] 的一个忠告', 'dont_only'],
  ['24', '[指出特征] 的人', 'not_a_but_b'],
  ['25', '给 [一群人] 的最好忠告', 'checklist_ready'],
  ['26', '[数字] 个达成 [结果] 的小窍门', 'checklist_ready'],
  ['27', '[话题] 的 [数字] 个步骤', 'roadmap_planning'],
  ['28', '[结果] 的 [数字] 个技巧', 'checklist_ready'],
  ['29', '[行动] 时，[数字] 个最有用的词', 'checklist_ready'],
  ['30', '让你更 [结果] 的 [数字] 个方法', 'checklist_ready'],
  ['31', '[数字] 个让你 [结果] 的特质', 'checklist_ready'],
  ['32', '[数字] 个 [话题] 的最大谎言', 'not_a_but_b'],
  ['33', '如何不 [讨厌的事]，就能在 [时间] 里达到 [结果]', 'roadmap_planning'],
  ['34', '[数字] 天内 [结果] 的唯一办法', 'exam_rescue'],
  ['35', '我如何在 [时间] 内 [结果]', 'roadmap_planning'],
  ['36', '没有 [资源]，也能 [结果]', 'not_a_but_b'],
  ['37', '如何把 [小数] 变成 [大数]', 'roadmap_planning'],
  ['38', '[结果]，头 [数字] 小时你需要做什么', 'exam_rescue'],
  ['39', '一招就能帮你带来三倍 [结果]', 'not_a_but_b'],
  ['40', '如何 [行动]，好让你 [结果]', 'roadmap_planning'],
  ['41', '我是如何从 [不想要的结果] 到 [想要的结果]', 'effort_failed'],
  ['42', '从 [经历] 中学到的最重要的教训', 'mistake_warning'],
  ['43', '我是如何在没有 [资源] 的情况下 [结果]', 'not_a_but_b'],
  ['44', '[话题] - 买家秀/成功案例', 'checklist_ready'],
  ['45', '[负面事件] 是如何带给我 [正面结果] 的', 'not_a_but_b'],
  ['46', '我差一点就 [负面的事]', 'mistake_warning'],
  ['47', '从 [经历] 中我所学到的', 'mistake_warning'],
  ['48', '[行动] 是在浪费时间么？', 'not_a_but_b'],
  ['49', '[结果] 会让你快乐么？', 'not_a_but_b'],
  ['50', '[行动] 会不会是你做过的最好决定？', 'not_a_but_b'],
  ['51', '[已经过时了] 么？', 'not_a_but_b'],
  ['52', '[好的特质] VS [坏的特质] - 如何区分', 'compare_choice'],
  ['53', '[一群人] 是天生的，还是后天养成的', 'compare_choice'],
  ['54', '停止 [行动]！！开始 [行动]！！', 'dont_only'],
  ['55', '你到底要不要 [话题]', 'compare_choice'],
  ['56', '如果你 [抗拒] [抗拒] [抗拒]，如何解决 [问题]', 'roadmap_planning'],
  ['57', '在 [人生阶段] 之后，你需要做的事情', 'roadmap_planning'],
  ['58', '当 [一群人] 说「[引用]」', 'not_a_but_b'],
  ['59', '如果你可以拿 [拥有的] 换 [可以拥有的]，你愿意么？', 'compare_choice'],
  ['60', '当你知道你会 [负面情绪]，如何 [结果]', 'roadmap_planning'],
  ['61', '为什么你应该停止 [行动]', 'dont_only'],
  ['62', '别再关心 [话题]', 'dont_only'],
  ['63', '别再寻找 [结果]，开始行动才是王道', 'dont_only'],
  ['64', '戒掉 [平常的事] - 这会让你和别人不一样', 'dont_only'],
  ['65', '为什么我 [讨厌做的事]，你也应该这么做', 'not_a_but_b'],
  ['66', '如何每天 [积极的事]，哪怕你 [不方便] 都可以', 'roadmap_planning'],
  ['67', '[名人] [话题] 帮助我 [结果]', 'not_a_but_b'],
  ['68', '[名人] 教会我 [话题] 的技能', 'not_a_but_b'],
  ['69', '[名人] 如何 [结果]', 'not_a_but_b'],
  ['70', '最好的 [一群人] 都做了什么不同的事情？', 'not_a_but_b'],
  ['71', '[一群人] [做一件事] 成功的最根本原因', 'not_a_but_b'],
  ['72', '敢不敢测一测，[话题]', 'checklist_ready'],
  ['73', '如果你想要 [结果]，你需要先对它着迷', 'roadmap_planning'],
  ['74', '关于 [话题]，我的处世哲学/原则', 'checklist_ready'],
  ['75', '至关紧要的头 [数字] 分钟 - 如何 [话题]', 'exam_rescue'],
];

const hotTitles: HotTitle[] = formulaRows.map(([id, formula, template]) => ({
  id: `formula_${id}`,
  source_title: formula,
  extracted_structure: formula,
  suitable_title_template: template,
  notes: '原始爆款标题公式，使用时只套入当前商品、人群、痛点和具体资料点。',
}));

const data: SkillData = {
  products: {
    delf_b2_writing: {
      id: 'delf_b2_writing',
      name: 'DELF B2 写作知识库',
      public_name_options: ['DELF B2 写作知识库', 'DELF B2 写作资料包', 'B2 写作范文句型训练包'],
      core_audience: ['DELF B2 考生', 'B1 到 B2 过渡阶段', '背范文但不会迁移的人', '写作不像 B2 的人', '临考前想系统整理写作的人'],
      preset_selling_points: [
        { id: 'essay_library_20', name: '20 篇范文库', suitable_angles: ['范文拆解', '不是整篇硬背', '多题型可迁移'] },
        { id: 'score_rubric', name: 'DELF B2 评分对照', suitable_angles: ['知道考官看什么', '按评分项自查', '避免低级失分'] },
        { id: 'vocab_240', name: '240 条 B2 词汇库', suitable_angles: ['普通词升级', '高频替换词', '表达更像 B2'] },
        { id: 'syntax_100', name: '100 条句法库', suitable_angles: ['观点展开', '让步转折', '句子结构升级'] },
        { id: 'topic_opinions_50', name: '50 条主题观点库', suitable_angles: ['没观点可写', '开头和论点卡住', '高频主题储备'] },
        { id: 'mistake_contrast_30', name: '30 条错题对照库', suitable_angles: ['普通写法 vs B2 写法', '看着没错但不像 B2'] },
        { id: 'checklist_36', name: '36 项写作检查清单', suitable_angles: ['考前自查', '写完检查', '减少漏项'] },
        { id: 'exam_sprint', name: '考前冲刺速查', suitable_angles: ['临考复盘', '最后几天看什么', '高频表达速查'] },
      ],
      seo_keywords: {
        core: ['DELF B2', 'DELF B2 写作', '法语 B2', '法语写作'],
        long_tail: ['DELF B2 写作范文', 'DELF B2 写作模板', '法语 B2 作文', '法语写作替换词', 'DELF B2 production écrite'],
      },
      default_tags: ['#DELFB2', '#法语B2', '#法语写作', '#法语作文', '#法语考试', '#DELF备考'],
    },
    tef_tcf_canada: {
      id: 'tef_tcf_canada',
      name: 'TEF/TCF Canada 备考知识库',
      public_name_options: ['TEF/TCF Canada 备考知识库', '法语移民 CLB7 备考资料包', 'TEF/TCF Canada 30 天备考包'],
      core_audience: ['加拿大移民申请人', '目标 CLB7 的法语考生', '不知道选 TEF 还是 TCF 的人', '备考时间短的上班族', '听说写某一项明显拖后腿的人'],
      preset_selling_points: [
        { id: 'exam_choice', name: 'TEF/TCF 选考指南', suitable_angles: ['TEF 还是 TCF', '选考避坑', '先判断适配度'] },
        { id: 'clb7_self_test', name: 'CLB7 差距自测', suitable_angles: ['现在离 CLB7 多远', '先测再练', '不要盲目刷题'] },
        { id: 'writing_patterns_50', name: '50 个写作提分句型', suitable_angles: ['TEF/TCF 写作', '直接拿来用', '输出训练'] },
        { id: 'vocab_600', name: '12 大类 600 词', suitable_angles: ['背词不迷路', '按主题背', '写作口语都能用'] },
        { id: 'topics_full', name: '高频真题主题库', suitable_angles: ['知道练什么', '主题全收录', '避免偏题'] },
        { id: '30_day_plan', name: '30 天每天 2 小时计划', suitable_angles: ['上班族备考', '每天练什么', '阶段安排'] },
        { id: 'listening_speaking', name: '听力口语训练方法', suitable_angles: ['急不来但能拆', '开口没那么可怕', '弱项补救'] },
        { id: 'pitfall_30', name: '30 条吐血避坑经验', suitable_angles: ['少走弯路', '考前流程', '报名到查分'] },
      ],
      seo_keywords: {
        core: ['TEF Canada', 'TCF Canada', '加拿大移民', 'CLB7'],
        long_tail: ['TEF Canada 和 TCF Canada 区别', '加拿大移民法语考试', 'TEF/TCF 30 天备考', 'CLB7 备考', 'TEF 写作', 'TCF 写作'],
      },
      default_tags: ['#TEFCanada', '#TCFCanada', '#加拿大移民', '#法语移民', '#CLB7', '#法语考试'],
    },
  } as Record<ProductId, SkillData['products'][ProductId]>,

  chains: {
    delf_b2_formula_migration: {
      id: 'delf_b2_formula_migration',
      name: 'DELF B2｜背范文不会迁移',
      version_scope: 'v1_core',
      product_id: 'delf_b2_writing',
      content_intent: '解决背了范文、换题还是不会写的问题，重点讲范文拆解和表达迁移。',
      allowed_content_source_types: ['preset_selling_point', 'knowledge_point', 'third_party_post'],
      recommended_product_points: ['essay_library_20', 'syntax_100', 'topic_opinions_50'],
      allowed_cover_templates: ['white_blue_pain', 'document_sample', 'list_poster'],
      allowed_title_templates: ['effort_failed', 'not_a_but_b', 'dont_only', 'checklist_ready'],
      allowed_page_templates: ['pain_breakdown', 'sample_showcase', 'list_value'],
      example_cover_titles: ['范文背熟了\n换题还是不会写？', '不是范文没背够\n是不会拆出来用'],
      required_inputs: ['具体痛点或原帖内容', '至少 1 个可展示例子：范文片段/句型/迁移前后对照'],
      forbidden_terms: ['CLB7', '加拿大移民', 'TEF Canada', 'TCF Canada'],
      conflict_notes: '不要把 DELF B2 写作写成 TEF/TCF Canada 移民备考。',
    },
    delf_b2_expression_upgrade: {
      id: 'delf_b2_expression_upgrade',
      name: 'DELF B2｜普通表达升级',
      version_scope: 'v1_core',
      product_id: 'delf_b2_writing',
      content_intent: '把 important / problème / je pense que 等普通表达升级为更像 B2 的表达。',
      allowed_content_source_types: ['preset_selling_point', 'knowledge_point'],
      recommended_product_points: ['vocab_240', 'mistake_contrast_30'],
      allowed_cover_templates: ['table_compare', 'list_poster', 'document_sample'],
      allowed_title_templates: ['dont_only', 'mistake_warning', 'checklist_ready', 'not_a_but_b'],
      allowed_page_templates: ['table_compare', 'list_value', 'mistake_compare'],
      example_cover_titles: ['别再把\nimportant 写到底', '这些词没错\n但不像 B2'],
      required_inputs: ['至少 3 组普通表达 -> B2 表达对照'],
      forbidden_terms: ['CLB7', '加拿大移民', 'TEF Canada', 'TCF Canada'],
      conflict_notes: '如果只有一个单词替换，不足以生成 7 页，先补充更多对照。',
    },
    delf_b2_sentence_patterns: {
      id: 'delf_b2_sentence_patterns',
      name: 'DELF B2｜句法库/模板拆解',
      version_scope: 'v1_core',
      product_id: 'delf_b2_writing',
      content_intent: '展示开头句、观点句、让步句、转折句、总结句等可迁移句法。',
      allowed_content_source_types: ['preset_selling_point', 'knowledge_point'],
      recommended_product_points: ['syntax_100', 'checklist_36'],
      allowed_cover_templates: ['list_poster', 'document_sample', 'white_blue_pain'],
      allowed_title_templates: ['checklist_ready', 'exam_rescue', 'dont_only', 'roadmap_planning'],
      allowed_page_templates: ['list_value', 'sample_showcase'],
      example_cover_titles: ['B2 写作\n这 12 句真能救急', '别再整篇背模板\n先拆这几类句子'],
      required_inputs: ['至少 5 条句型或 3 类句型功能'],
      forbidden_terms: ['CLB7', '加拿大移民', 'TEF Canada', 'TCF Canada'],
      conflict_notes: '',
    },
    delf_b2_mistake_contrast: {
      id: 'delf_b2_mistake_contrast',
      name: 'DELF B2｜错题对照/扣分点',
      version_scope: 'v1_core',
      product_id: 'delf_b2_writing',
      content_intent: '展示中式表达、低级表达、逻辑断裂、看似没错但不像 B2 的写法。',
      allowed_content_source_types: ['preset_selling_point', 'knowledge_point', 'third_party_post'],
      recommended_product_points: ['mistake_contrast_30', 'checklist_36', 'vocab_240'],
      allowed_cover_templates: ['mistake_compare', 'table_compare', 'white_blue_pain'],
      allowed_title_templates: ['mistake_warning', 'dont_only', 'not_a_but_b'],
      allowed_page_templates: ['mistake_compare', 'table_compare', 'pain_breakdown'],
      example_cover_titles: ['B2 写作\n这几种写法很掉分', '这些句子没大错\n但不像 B2'],
      required_inputs: ['至少 2-3 组错误写法 -> 优化写法对照'],
      forbidden_terms: ['CLB7', '加拿大移民', 'TEF Canada', 'TCF Canada'],
      conflict_notes: '不要伪造评分，不要假装官方判卷意见。',
    },
    tef_tcf_exam_choice: {
      id: 'tef_tcf_exam_choice',
      name: 'TEF/TCF｜TEF 还是 TCF',
      version_scope: 'v1_core',
      product_id: 'tef_tcf_canada',
      content_intent: '帮助用户理解 TEF Canada 和 TCF Canada 的差异与选择逻辑。',
      allowed_content_source_types: ['preset_selling_point', 'knowledge_point', 'third_party_post'],
      recommended_product_points: ['exam_choice', 'pitfall_30'],
      allowed_cover_templates: ['table_compare', 'list_poster', 'white_blue_pain'],
      allowed_title_templates: ['compare_choice', 'checklist_ready', 'not_a_but_b', 'mistake_warning'],
      allowed_page_templates: ['table_compare', 'list_value', 'pain_breakdown'],
      example_cover_titles: ['TEF 还是 TCF？\n先看这 5 个差异', '加拿大法语考试\n别选完才后悔'],
      required_inputs: ['至少 3 个 TEF/TCF 对比维度'],
      forbidden_terms: ['DELF B2 production écrite', 'DELF B2 范文', 'B2 写作资料包'],
      conflict_notes: '不要承诺哪个更容易拿分，只说明选择参考。',
    },
    tef_tcf_30_day_clb7: {
      id: 'tef_tcf_30_day_clb7',
      name: 'TEF/TCF｜30 天备考/CLB7 路径',
      version_scope: 'v1_core',
      product_id: 'tef_tcf_canada',
      content_intent: '30 天备考安排、CLB7 目标拆解、阶段任务和资料使用顺序。',
      allowed_content_source_types: ['preset_selling_point', 'knowledge_point', 'third_party_post'],
      recommended_product_points: ['30_day_plan', 'clb7_self_test', 'writing_patterns_50'],
      allowed_cover_templates: ['plan_table', 'list_poster', 'document_sample'],
      allowed_title_templates: ['roadmap_planning', 'exam_rescue', 'checklist_ready', 'effort_failed', 'dont_only'],
      allowed_page_templates: ['plan_calendar', 'roadmap', 'list_value'],
      example_cover_titles: ['TEF/TCF Canada\n30 天冲 CLB7 怎么排', '别再每天瞎刷题\nCLB7 要这样拆'],
      required_inputs: ['目标分数/CLB7 场景', '至少 3 个阶段任务或 1 张计划表'],
      forbidden_terms: ['DELF B2 production écrite', 'DELF B2 范文', 'B2 写作资料包'],
      conflict_notes: '不要把 CLB7 和 DELF B2 混用。',
    },
  } as Record<ChainId, SkillData['chains'][ChainId]>,

  cover_templates: {
    white_blue_pain: {
      id: 'white_blue_pain', name: '纯文字痛点模板', purpose: '点击', similarity_mode: 'high_similarity_allowed',
      description: '白底蓝字、大留白、强痛点。适合反常识、努力无效、备考焦虑。',
      suitable_content: ['痛点', '努力无效', '反常识', '备考误区'],
      canvas: { ratio: '3:4', size: '1080x1440' },
      layout_rules: { background: '白底或极浅蓝', title_position: '中部偏上', title_lines: '2-4 行' },
      variable_fields: ['主标题', '副标题', '底部提示'],
      locked_fields: ['白底', '蓝色大标题', '大留白', '2-4 行标题'],
      forbidden: ['不要做成资料清单', '不要堆太多卖点', '不要过度装饰'],
    },
    list_poster: {
      id: 'list_poster', name: '清单整理模板', purpose: '收藏 + 转化',
      suitable_content: ['替换词', '高频句型', '备考清单', '30 天计划', '资料目录'],
      canvas: { ratio: '3:4', size: '1080x1440' },
      layout_rules: { background: '浅色底', title_position: '顶部', content_density: '中高' },
      variable_fields: ['标题', '清单条目', '数量'],
      locked_fields: ['标题 + 清单预览', '数字感或条目感'],
      forbidden: ['不要只有一句话', '不要变成纯痛点封面'],
    },
    table_compare: {
      id: 'table_compare', name: '表格对照模板', purpose: '收藏 + 搜索',
      suitable_content: ['普通表达 vs B2 表达', 'TEF vs TCF', '错误写法 vs 优化写法', '低效备考 vs 高效备考'],
      canvas: { ratio: '3:4', size: '1080x1440' },
      layout_rules: { background: '白底或浅色卡片', title_position: '顶部', table_columns: 2 },
      variable_fields: ['表头', '左列', '右列'],
      locked_fields: ['顶部标题 + 两列表格'],
      forbidden: ['不要只放段落', '不要让表格信息太满'],
    },
    document_sample: {
      id: 'document_sample', name: '资料样张模板', purpose: '展示质量 + 转化',
      suitable_content: ['范文拆解', '检查清单', '主题观点库', '资料目录', '样张展示'],
      canvas: { ratio: '3:4', size: '1080x1440' },
      layout_rules: { background: '白底或浅灰文档背景', title_position: '顶部或左上' },
      variable_fields: ['标题', '文档样张', '标注'],
      locked_fields: ['文档/讲义截图感', '资料样张露出'],
      forbidden: ['不要做成纯海报', '不要泄露过多完整付费内容'],
    },
    case_review: {
      id: 'case_review', name: '案例复盘模板', purpose: '信任',
      suitable_content: ['过来人案例', '失败复盘', '备考误区', '第三方帖子经验'],
      canvas: { ratio: '3:4', size: '1080x1440' },
      layout_rules: { background: '浅色文档或复盘感', title_position: '顶部' },
      variable_fields: ['案例标题', '复盘要点'],
      locked_fields: ['案例标题 + 复盘摘要'],
      forbidden: ['不要伪造真实聊天记录'],
    },
    mistake_compare: {
      id: 'mistake_compare', name: '错题批注模板', purpose: '收藏 + 避坑',
      suitable_content: ['常见错误', '错误写法 vs 优化写法', '扣分点', '中式表达'],
      canvas: { ratio: '3:4', size: '1080x1440' },
      layout_rules: { background: '白底或浅蓝底', title_position: '顶部' },
      variable_fields: ['错误句', '优化句', '批注'],
      locked_fields: ['错误/正确对照', '批注感'],
      forbidden: ['不要伪造官方评分'],
    },
    plan_table: {
      id: 'plan_table', name: '计划表模板', purpose: '收藏 + 执行',
      suitable_content: ['30 天计划', '备考日历', '阶段路径', 'CLB7 路径'],
      canvas: { ratio: '3:4', size: '1080x1440' },
      layout_rules: { background: '浅色底', title_position: '顶部', content_density: '中高' },
      variable_fields: ['阶段', '时间', '任务'],
      locked_fields: ['标题 + 计划表/时间轴', '数字时间感'],
      forbidden: [],
    },
  } as Record<CoverTemplateId, SkillData['cover_templates'][CoverTemplateId]>,

  title_templates: {
    effort_failed: {
      id: 'effort_failed', name: '努力无效型',
      reference_examples: ['范文背熟了，题目一变又不会了', '题刷了很多，分数还是上不去'],
      structure: { formula: '[已做努力] + [场景变化] + [结果仍失败]', psychological_hook: '用户已经努力过，但结果没有变好。' },
      suitable_content: ['背范文不会迁移', '刷题但 CLB7 卡住', '句型背了但不会写', '学了很多但不会用'],
    },
    not_a_but_b: {
      id: 'not_a_but_b', name: '反常识型',
      reference_examples: ['最怕的不是 A，而是 B', '不是没背范文，是不会拆出来用'],
      structure: { formula: '不是 [表面问题]，而是 [真正问题]', psychological_hook: '推翻用户原来的理解。' },
      suitable_content: ['不是语法错而是表达低级', '不是刷题少而是规划错', '不是没背而是不会拆'],
    },
    dont_only: {
      id: 'dont_only', name: '别再型',
      reference_examples: ['别再只会 XXX 了', '别再整篇背模板了'],
      structure: { formula: '别再 + [低效做法/低级表达]', psychological_hook: '提醒用户停止错误动作。' },
      suitable_content: ['important 替换', '整篇背范文', '只刷题不复盘'],
    },
    compare_choice: {
      id: 'compare_choice', name: '对比选择型',
      reference_examples: ['A 还是 B？先看这 5 个差异', '到底选 A 还是 B？'],
      structure: { formula: '[选项 A] 还是 [选项 B]？先看 [数字] 个差异', psychological_hook: '帮用户做选择。' },
      suitable_content: ['TEF vs TCF', '两种备考路径', '普通写法 vs B2 写法'],
    },
    checklist_ready: {
      id: 'checklist_ready', name: '清单整理型',
      reference_examples: ['XX 表，我整理好了', 'XX 清单，照着做'],
      structure: { formula: '[具体资料/清单/计划]，我整理好了', psychological_hook: '降低用户整理成本。' },
      suitable_content: ['30 天计划', '替换词清单', '写作检查清单', '高频句型'],
    },
    mistake_warning: {
      id: 'mistake_warning', name: '错误提醒型',
      reference_examples: ['这些句子没大错，但不像 B2', '这个写法看着没错，但很难高分'],
      structure: { formula: '[内容] 没大错，但 [不符合目标水平/不利得分]', psychological_hook: '指出用户意识不到的问题。' },
      suitable_content: ['错题对照', '普通写法 vs B2 写法', '低级表达'],
    },
    exam_rescue: {
      id: 'exam_rescue', name: '考前急救型',
      reference_examples: ['考前 10 天，这份清单先看完', 'B2 写作临考前，先别乱背了'],
      structure: { formula: '[考试/任务] + [临近时间] + [先做这个]', psychological_hook: '临近考试时降低决策成本。' },
      suitable_content: ['考前清单', '高频句型', '写作检查清单', '30 天/10 天计划'],
    },
    roadmap_planning: {
      id: 'roadmap_planning', name: '路径规划型',
      reference_examples: ['30 天冲 CLB7，别再每天瞎刷题', 'TEF/TCF Canada 30 天怎么排'],
      structure: { formula: '[目标] + [时间/路径] + [怎么安排]', psychological_hook: '把混乱备考变成可执行路径。' },
      suitable_content: ['30 天备考', 'CLB7 路径', '资料使用顺序', '阶段规划'],
    },
  } as Record<TitleTemplateId, SkillData['title_templates'][TitleTemplateId]>,

  page_templates: {
    pain_breakdown: { id: 'pain_breakdown', name: '痛点拆解型', suitable_for: ['努力无效', '背了但不会用', '写作卡住'], page_count: 7, recommended_single_page_formats: ['conclusion_bullets'], structure: { P1: '封面', P2: '先说结论', P3: '问题是什么', P4: '为什么会这样', P5: '正确做法', P6: '资料包怎么解决', P7: '适合谁' } },
    list_value: { id: 'list_value', name: '清单干货型', suitable_for: ['替换词', '高频句型', '备考清单'], page_count: 7, recommended_single_page_formats: ['conclusion_bullets', 'table'], structure: { P1: '封面', P2: '为什么这份清单重要', P3: '清单 1', P4: '清单 2', P5: '怎么用', P6: '完整资料有什么', P7: '适合谁' } },
    table_compare: { id: 'table_compare', name: '表格对照型', suitable_for: ['TEF vs TCF', '表达对照', '错误对照'], page_count: 7, recommended_single_page_formats: ['table'], structure: { P1: '封面', P2: '先给结论', P3: '对照表 1', P4: '对照表 2', P5: '怎么判断', P6: '资料包对应模块', P7: '收口' } },
    sample_showcase: { id: 'sample_showcase', name: '样张展示型', suitable_for: ['范文拆解', '检查清单', '资料目录'], page_count: 7, recommended_single_page_formats: ['sample_annotation'], structure: { P1: '封面', P2: '不要怎么用', P3: '样张 1', P4: '样张 2', P5: '样张标注', P6: '完整资料结构', P7: '适合谁' } },
    case_review: { id: 'case_review', name: '案例复盘型', suitable_for: ['案例', '失败复盘', '备考误区'], page_count: 7, recommended_single_page_formats: ['conclusion_bullets'], structure: { P1: '封面', P2: '案例背景', P3: '踩坑点 1', P4: '踩坑点 2', P5: '调整方式', P6: '资料包怎么整理', P7: '适合谁' } },
    roadmap: { id: 'roadmap', name: '攻略路径型', suitable_for: ['30 天计划', '学习路径', '资料使用顺序'], page_count: 7, recommended_single_page_formats: ['steps'], structure: { P1: '封面', P2: '适合谁', P3: '第 1 阶段', P4: '第 2 阶段', P5: '第 3 阶段', P6: '资料怎么用', P7: '收尾' } },
    mistake_compare: { id: 'mistake_compare', name: '错题对照型', suitable_for: ['错题对照', '扣分点', '中式表达'], page_count: 7, recommended_single_page_formats: ['wrong_right'], structure: { P1: '封面', P2: '为什么不像目标水平', P3: '错误写法 1', P4: '错误写法 2', P5: '错误写法 3', P6: '资料包错题模块', P7: '适合谁' } },
    plan_calendar: { id: 'plan_calendar', name: '计划日历型', suitable_for: ['30 天计划', 'CLB7 路径', '阶段备考'], page_count: 7, recommended_single_page_formats: ['steps', 'table'], structure: { P1: '封面', P2: '目标是什么', P3: '第 1 阶段', P4: '第 2 阶段', P5: '第 3 阶段', P6: '资料怎么按阶段用', P7: '提醒' } },
  } as Record<PageTemplateId, SkillData['page_templates'][PageTemplateId]>,

  copy_formats: {
    conclusion_bullets: { id: 'conclusion_bullets', name: '结论 + 3 条 bullet', structure: ['页标题', '一句核心结论', '3 条 bullet'], word_limit: { conclusion: '20-40 字', bullet: '8-22 字' } },
    wrong_right: { id: 'wrong_right', name: '错误/正确对照', structure: ['普通写法', '问题说明', '优化写法', '为什么更好'], word_limit: { explanation: '20-50 字' } },
    table: { id: 'table', name: '表格型', structure: ['表头', '3-6 行对照', '一句使用提醒'], word_limit: { table_cell: '每格 4-18 字' } },
    sample_annotation: { id: 'sample_annotation', name: '样张标注型', structure: ['样张片段', '标注 1', '标注 2', '标注 3'], word_limit: { annotation: '每条 8-24 字' } },
    steps: { id: 'steps', name: '步骤型', structure: ['阶段标题', '步骤 1', '步骤 2', '步骤 3'], word_limit: { step: '每步 10-24 字' } },
  } as Record<CopyFormatId, SkillData['copy_formats'][CopyFormatId]>,

  hot_titles: hotTitles,

  seo_tags: {
    delf_b2_writing: {
      core_keywords: ['DELF B2', 'DELF B2 写作', '法语 B2', '法语写作'],
      long_tail_keywords: ['DELF B2 写作范文', 'DELF B2 写作模板', '法语 B2 作文', '法语写作替换词', '法语高级句型'],
      tags: ['#DELFB2', '#法语B2', '#法语写作', '#法语作文', '#法语考试', '#DELF备考'],
    },
    tef_tcf_canada: {
      core_keywords: ['TEF Canada', 'TCF Canada', '加拿大移民', '法语移民', 'CLB7'],
      long_tail_keywords: ['TEF Canada 和 TCF Canada 区别', '加拿大移民法语考试', 'TEF/TCF 30 天备考', 'CLB7 备考', 'TEF 写作', 'TCF 写作'],
      tags: ['#TEFCanada', '#TCFCanada', '#加拿大移民', '#法语移民', '#CLB7', '#法语考试'],
    },
  } as Record<ProductId, SkillData['seo_tags'][ProductId]>,

  compatibility_matrix: {
    principle: '先选商品，再选链路；封面母版、标题母版、内页结构只能从链路允许范围里选。',
    global_forbidden: ['官方保证', '内部题库', '押中原题'],
    product_forbidden_terms: {
      delf_b2_writing: ['CLB7', '加拿大移民', 'TEF Canada', 'TCF Canada'],
      tef_tcf_canada: ['DELF B2 production écrite', 'DELF B2 范文', 'B2 写作资料包'],
    },
    state_required_fields: {
      before_content: ['product_id', 'chain_id'],
      before_cover_generation: ['product_id', 'chain_id', 'content_source_type', 'content_core', 'cover_template_id', 'title_template_id'],
      before_page_generation: ['selected_variant_id'],
      before_caption_generation: ['page_scripts'],
    },
    content_volume_rules: {
      knowledge_point_minimum: '必须有具体对照、例句、清单或样张。只有标签不得生成。',
      short_content_action: '内容量不足时先要求补充，或降级为短图文。',
    },
    title_hot_title_rule: '75 个标题公式不是自由乱用，必须先归类到标题母版，再按当前商品、人群、痛点改写。',
    visual_rule: '封面母版决定视觉风格，标题只决定语义钩子，二者必须兼容。',
  },
};

export default data;

export function getStaticSkillData(): SkillData {
  return data;
}
