import nextEnv from '@next/env';
import {readFile, mkdir, writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {buildNativeTitlePrompt,extractNativeTitleCandidates} from '../src/lib/v2/native-title-skill';
import {generateTitlePackage, filterTextTitleCandidates, TEXT_MODEL} from '../src/lib/v2/title-stage';
import {stableHash} from '../src/lib/v2/contracts';
import {FACT_BOUNDARY_VERSION} from '../src/lib/v2/note-fact-boundary';
import {callOpenAICompatibleJsonWithUsage} from '../src/lib/ai-client';
import {getCompetitorCreativeCard} from '../src/lib/creative-card-library';
import {getCapabilityFallback} from '../src/lib/v2/topic-stage';
nextEnv.loadEnvConfig(process.cwd());
const job=JSON.parse(await readFile('data/batches/batch_1788974717737/jobs/job_002.json','utf8'));
const content=structuredClone(job.artifacts.content.data);
delete content.autoFactBrief;
const input={topic:job.artifacts.selectedTopic.data,content,capability:getCapabilityFallback(getCompetitorCreativeCard(job.reference_card_id)!)};
const prompt=buildNativeTitlePrompt(input);
assert.equal(prompt.systemPrompt,await readFile(prompt.skillPath,'utf8'));
for(const page of content.innerPages)for(const bullet of page.bullets)if(typeof bullet==='string')assert.ok(prompt.userPrompt.includes(bullet));
assert.equal('scopeMode' in prompt.titleCoreInput,false);
assert.equal('factBrief' in prompt.titleCoreInput,false);
const fixture='## ② 候选标题矩阵\n| # | 候选标题 | 字符数 | 方法 | 钩子/搜索词 | 评分 | 风险 |\n|---|---|---|---|---|---|---|\n| 1 | **B2写作怎么下笔？** | 10 | 搜索 | B2写作 | 85 | 低 |\n| 2 | B2写作\\|终于有思路 | 12 | 情绪 | B2写作 | 90 | 低 |\n\n## 推荐\n| 1 | 不应重复提取 |';
assert.deepEqual(extractNativeTitleCandidates(fixture).map(c=>c.textTitle),['B2写作怎么下笔？','B2写作|终于有思路']);
assert.deepEqual(extractNativeTitleCandidates(fixture.replace('\n| 2 |','\n\n| 2 |')).map(c=>c.textTitle),['B2写作怎么下笔？','B2写作|终于有思路']);
assert.throws(()=>extractNativeTitleCandidates(fixture.replace('B2写作\\|终于有思路','B2写作|终于有思路')),/NATIVE_TITLE_MATRIX_INVALID/);
assert.equal(TEXT_MODEL,'deepseek-flash');
const boundaryContent=structuredClone(content);
boundaryContent.autoFactBrief={boundaryVersion:FACT_BOUNDARY_VERSION,sourceInnerHash:stableHash(content.innerPages),
  factBrief:'事实摘要测试',userTask:'用户任务测试',noteCore:'整篇核心测试',deliverables:['交付测试'],
  supportedCounts:[],scopedFacts:[],scopeNotes:['范围测试'],doNotReframe:['改义测试']};
const grounded=buildNativeTitlePrompt({...input,content:boundaryContent,recentGeneratedTextTitles:['历史候选测试']});
for(const text of ['事实摘要测试','用户任务测试','整篇核心测试','交付测试','范围测试','改义测试','历史候选测试']) assert.ok(grounded.userPrompt.includes(text));
assert.equal(grounded.systemPrompt,prompt.systemPrompt);
boundaryContent.autoFactBrief.sourceInnerHash='stale';
assert.equal(buildNativeTitlePrompt({...input,content:boundaryContent}).titleCoreInput.factBoundary,undefined);
const parsed=extractNativeTitleCandidates(fixture);
const evaluated=filterTextTitleCandidates(parsed,input).evaluated;
assert.equal(evaluated[0].candidate.method,'搜索');
assert.equal(evaluated[0].candidate.hookOrSearchTerm,'B2写作');
assert.equal(evaluated[0].candidate.score,85);
assert.equal(evaluated[0].candidate.risk,'低');
const audienceInput={...input,topic:{...input.topic,audienceState:'打工人下班备考'}};
assert.ok(!filterTextTitleCandidates([{textTitle:'打工人备考法语，先练什么？'}],audienceInput).evaluated[0].filterReasons.includes('UNSUPPORTED_AUDIENCE_IDENTITY'));
assert.ok(filterTextTitleCandidates([{textTitle:'宝妈备考法语，先练什么？'}],audienceInput).evaluated[0].filterReasons.includes('UNSUPPORTED_AUDIENCE_IDENTITY'));
const nuancedInput={...input,content:{...input.content,innerPages:[{page_no:1,page_title:'语域',lead:'根据语境判断，并非一律错误。',bullets:['on和ça并非一律错误；TEF Canada训练顺序。']}]}};
assert.ok(!filterTextTitleCandidates([{textTitle:'TEF Canada别用平均分配法'}],nuancedInput).evaluated[0].filterReasons.includes('CONTENT_CONTRADICTION'));
assert.ok(filterTextTitleCandidates([{textTitle:'B2写作不要用on'}],nuancedInput).evaluated[0].filterReasons.includes('CONTENT_CONTRADICTION'));
console.log('PASS: Flash unchanged, complete Skill, valid scoped facts, stale facts excluded, history input, native metadata retained');
console.log('OFFLINE PASS: original skill bytes, complete content, no brief dependency, exact extraction');
if(process.argv.includes('--live')) {
  const dir='data/native-title-acceptance/'+Date.now();await mkdir(dir,{recursive:true});
  const direct=await callOpenAICompatibleJsonWithUsage<string>([{role:'system',content:prompt.systemPrompt},{role:'user',content:prompt.userPrompt}],{stage:'title',model:'deepseek-flash',temperature:0.72,maxTokens:10000,retries:1,thinking:false,responseMode:'text'});
  await writeFile(dir+'/direct.md',direct.data);
  const production=await generateTitlePackage(input);
  await writeFile(dir+'/production.json',JSON.stringify(production,null,2));
  await writeFile(dir+'/request.json',JSON.stringify(prompt,null,2));
  await writeFile(dir+'/usage.json',JSON.stringify({direct:direct.usage,production:production.usage},null,2));
  assert.equal(production.data.humanSelectedTextTitleId,null);
  const extracted=extractNativeTitleCandidates(production.data.nativeSkillReport!);
  for(const c of production.data.humanSelectableTextTitles!)assert.ok(extracted.some(r=>r.textTitle===c.textTitle));
  console.log(JSON.stringify({dir,direct:extractNativeTitleCandidates(direct.data),production:production.data.humanSelectableTextTitles,usage:{direct:direct.usage,production:production.usage}},null,2));
}
