import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {projectReadablePages} from '../src/lib/readable-inner-layout';
const root=process.cwd();
const replay=JSON.parse(await fs.readFile('data/batch-export-ui/result.json','utf8'));
const temp=await fs.mkdtemp(path.resolve('.tmp-readable-api-'));
process.env.INNER_REVIEW_TEST_DATA_DIR=path.join(temp,'batches');
const require=createRequire(import.meta.url);
const dictionaryPath=require.resolve('dictionary-fr');
require.cache[dictionaryPath]={id:dictionaryPath,filename:dictionaryPath,loaded:true,exports:{}} as NodeModule;
const store=require('../src/lib/batch-store');
const {NextRequest}=require('next/server');
const api=require('../src/app/api/batch/route');
globalThis.fetch=async()=>{throw new Error('NETWORK_FORBIDDEN');};
for(const action of replay.actions.filter((a:any)=>a.readable_page_plan)){
  const filename=path.join(root,'data/batches/batch_1788792510292/jobs',action.job_id+'.json');
  const original=await fs.readFile(filename,'utf8'),job=JSON.parse(original);
  const plan=action.readable_page_plan;
  const projected=projectReadablePages(job.draft.inner_pages,plan);
  assert.equal(projected.length,plan.pages.length);
  const invalid=structuredClone(plan);invalid.pages[0].slices[0].start++;
  assert.throws(()=>projectReadablePages(job.draft.inner_pages,invalid));
  const stale=structuredClone(plan);stale.sourceHash='stale';
  assert.throws(()=>projectReadablePages(job.draft.inner_pages,stale));
  const reversed=structuredClone(plan);reversed.pages.reverse();
  assert.throws(()=>projectReadablePages(job.draft.inner_pages,reversed));
  const missing=structuredClone(plan);missing.pages.pop();
  assert.throws(()=>projectReadablePages(job.draft.inner_pages,missing));
  const id='readable_'+job.id;
  await store.createPlannedBatchAtomic({id,product_id:job.product_id,created_at:new Date().toISOString(),status:'done',jobs:[]},[job]);
  const response=await api.POST(new NextRequest('http://offline/api/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...action,batch_id:id})}));
  assert.equal(response.status,200,await response.clone().text());
  const saved=await store.loadJob(id,job.id);
  assert.deepEqual(saved.draft.inner_pages,job.draft.inner_pages);
  assert.deepEqual(saved.artifacts.content,job.artifacts.content);
  assert.deepEqual(saved.draft.titlePackage,job.draft.titlePackage);
  assert.equal(saved.commercial.pageManifest.expectedPageIds.length,projected.length+1);
  assert.equal(await fs.readFile(filename,'utf8'),original);
  console.log(`${job.id}: ${job.draft.inner_pages.length} source pages -> ${projected.length} display pages; lossless offsets + actual API manifest PASS`);
}
console.log('REAL_AI_CALLS=0; PRODUCTION_WRITES=0; '+temp);
