import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const source=path.resolve('data/batches/batch_1788792510292/jobs/job_002.json');
const original=await fs.readFile(source);
const job=JSON.parse(original.toString());
const temp=await fs.mkdtemp(path.resolve('.tmp-cover-choice-'));
process.env.INNER_REVIEW_TEST_DATA_DIR=temp;
globalThis.fetch=async()=>{throw new Error('NETWORK_FORBIDDEN');};
const require=createRequire(import.meta.url);
const dictionaryPath=require.resolve('dictionary-fr');
require.cache[dictionaryPath]={id:dictionaryPath,filename:dictionaryPath,loaded:true,exports:{}} as NodeModule;
const {POST}=require('../src/app/api/batch/route');
const store=require('../src/lib/batch-store');
const {assertDraftTitleReadyForExport}=require('../src/lib/batch-export');
const batchId='batch_cover_choice_offline';
await store.createPlannedBatchAtomic({id:batchId,product_id:job.product_id,created_at:new Date().toISOString(),status:'planned',jobs:[]},[job]);
const requestId=job.artifacts.content.data.coverCopy.requestId;
async function select(templateId:string,expected=requestId){return POST(new Request('http://offline/api/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update_draft_state',batch_id:batchId,job_id:job.id,selected_cover_template_id:templateId,expected_cover_request_id:expected})}));}
const alternative=job.artifacts.content.data.coverCandidates.find((c:any)=>!c.rejectionReason&&c.templateId!==job.reference_card_id);
assert.ok(alternative);
assert.equal((await select(alternative.templateId,'stale')).status,409);
assert.equal((await select('nonexistent')).status,400);
const response=await select(alternative.templateId);
assert.equal(response.status,200,await response.clone().text());
const saved=(await response.json()).job;
assert.equal(saved.reference_card_id,alternative.templateId);
assert.equal(saved.draft.selectedCoverTemplateId,alternative.templateId);
assert.equal(saved.draft.cover.title,alternative.coverTitle);
assert.equal(saved.draft.coverSelection.confirmedTemplateId,alternative.templateId);
assert.equal(saved.status,'awaiting_review');
assert.equal(saved.cover_image_url,undefined);assert.equal(saved.image_task_id,undefined);
assert.equal(saved.commercial,undefined);assert.equal(saved.artifacts.compiledDraft,undefined);
assert.deepEqual(saved.artifacts.content.data.innerPages,job.artifacts.content.data.innerPages);
assert.deepEqual(saved.artifacts.titles,job.artifacts.titles);
assert.equal(saved.draft.selected_title,job.draft.selected_title);
assert.throws(()=>assertDraftTitleReadyForExport(saved.draft),/COVER_COPY_PENDING/);
const confirmedAgain=await select(alternative.templateId);
assert.equal(confirmedAgain.status,200);
const again=(await confirmedAgain.json()).job;
assert.throws(()=>assertDraftTitleReadyForExport(again.draft),/COVER_COPY_PENDING/);
// Confirmation of a completed legacy recommendation keeps its existing image usable.
await store.saveJob(batchId,job);
const unchanged=await select(job.reference_card_id);
assert.equal(unchanged.status,200);
const same=(await unchanged.json()).job;
assert.equal(same.cover_image_url,job.cover_image_url);
assert.doesNotThrow(()=>assertDraftTitleReadyForExport(same.draft));
assert.deepEqual(await fs.readFile(source),original);
console.log('PASS: real API; stale/invalid rejected; choice preserves Inner/Title, invalidates old image/export; confirmation alone cannot export incomplete downstream; legacy same cover preserved. REAL_AI_CALLS=0; PRODUCTION_WRITES=0; '+temp);
